<?php

require("../phpMQTT.php");

	
$mqtt = new phpMQTT("example.com", 1883, "phpMQTT Pub Example"); //Change client name to something unique

if ($mqtt->connect()) {
	//$mqtt->publish("bluerhinos/phpMQTT/examples/publishtest","Hello World! at ".date("r"),0);
	$mqtt->publish("40AEE8/switch/switch","ON"); //The MQTT string of the Sonoff/Wemos generated by https://github.com/mertenats/Open-Home-Automation code
	$mqtt->close();
}

?>
